# Generated by Django 5.0.14 on 2026-02-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, help_text='e.g. 1.0, 95, A', max_length=5, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('DROPPED', 'Dropped')], default='ONGOING', max_length=20)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='core.subject')),
            ],
            options={
                'unique_together': {('enrollment', 'subject')},
            },
        ),
    ]
