# Generated by Django 5.0.14 on 2026-02-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_address_student_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course/Degree'),
        ),
        migrations.AddField(
            model_name='student',
            name='college_school_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='College/University'),
        ),
        migrations.AddField(
            model_name='student',
            name='college_year_graduated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Graduated'),
        ),
        migrations.AddField(
            model_name='student',
            name='elem_school_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Elementary School'),
        ),
        migrations.AddField(
            model_name='student',
            name='elem_year_graduated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Graduated'),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_school_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Secondary School'),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_year_graduated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Graduated'),
        ),
    ]
