# Generated by Django 5.0.14 on 2026-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_nationality_student_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Filipino', 'Filipino'), ('American', 'American'), ('British', 'British'), ('Canadian', 'Canadian'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Australian', 'Australian'), ('Singaporean', 'Singaporean'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Roman Catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Evangelical', 'Evangelical'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Protestant', 'Protestant'), ('Buddhist', 'Buddhist'), ('Hindu', 'Hindu'), ('Seventh Day Adventist', 'Seventh Day Adventist'), ('Aglipay', 'Aglipay'), ('Other', 'Other'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
